name: Serverless Stack Update
description: |
  Update serverless stack and CDK versions. Runs the `sst update` command and commits the results. Requires that `@serverless-stack/cli` be installed as a dependency.

  If you want to make sure the automatic commit kicks of a new build, be sure to checkout the repo with a non-default token with Write permissions to the Pull Request.
runs:
  using: composite
  steps:
    - uses: actions/github-script@v6
      if: github.event.pull_request.user.login == 'renovate[bot]' && (contains(github.event.pull_request.title, 'serverless stack'))
      id: get-version
      with:
        result-encoding: string
        script: |
          const packageJSON = require('fs').readFileSync(`${{ github.workspace }}/package.json`).toString();
          const packageFile = JSON.parse(packageJSON);
          return packageFile.dependencies?.['@serverless-stack/cli'] ?? packageFile.devDependencies?.['@serverless-stack/cli'];

    - name: Update SST and CDK to Latest Versions
      if: github.event.pull_request.user.login == 'renovate[bot]' && (contains(github.event.pull_request.title, 'serverless stack'))
      shell: bash
      run: npx -p @serverless-stack/cli sst update ${{ steps.get-version.outputs.result }}

    - name: Commit updated dependencies
      if: github.event.pull_request.user.login == 'renovate[bot]' && (contains(github.event.pull_request.title, 'serverless stack'))
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: >
          chore(deps): update serverless stack to ${{ inputs.version }} and sync AWS CDK
