name: AWS Setup
description: Setup AWS
inputs:
  env:
    description: Env to setup
    required: false
    default: dev
  accounts:
    description: AWS Account Map
    required: true
  region:
    description: AWS Region
    required: true
    default: us-east-1
runs:
  using: "composite"
  steps:
    - name: Parse Accounts
      id: accounts
      uses: actions/github-script@v6
      with:
        script: |
          const accounts = JSON.parse(`${{ inputs.accounts }}`);
          const { id, name } = accounts[`${{ inputs.env }}`];
          return { id, name };
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ fromJSON(steps.accounts.outputs.result)['id'] }}:role/github/all/${{ fromJSON(steps.accounts.outputs.result)['name'] }}-gha-deployer
        aws-region: ${{ inputs.region }}
