name: Terraform Output
description: Takes in terraform command outputs and status and outputs a pretty summary
inputs:
  steps:
    description: "The steps object from context"
    required: true
  fmt:
    description: "The step id of the init step"
    required: false
  init:
    description: "The step id of the init step"
    required: true
  validate:
    description: "The step id of the validate step"
    required: false
  plan:
    description: "The step id of the plan step"
    required: false
  pr-id:
    description: Current PR's ID
    default: ${{ github.event.number }}
    required: true
  token:
    description: The GitHub token
    default: ${{ github.token }}
    required: true
  fail-on-error:
    description: "Wether or not to fail on a previous step's failure"
    default: "true"
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
