name: Release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install -g npm@">=7 <8"
      - run: npm ci

      - name: Create Release
        if: ${{ github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx auto shipit

      - name: Check Release
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx auto pr-check --url https://github.com/uShip/actions/actions/runs/${{ github.run_id }}
