on: pull_request

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: test-fail
        continue-on-error: true
        run: exit 1

      - uses: ./terraform-output
        with:
          steps: ${{ toJSON(steps) }}
